### ISSUE TITLE
How many times can we use jhipster-uml in the same project?

### ISSUE THREAD

**Issue by dhafirnz** [jhipster/jhipster-uml#139] opened 2016-02-08 06:40 UTC
Can we use jhipster-uml incrementally in the same project, or we have only one shot to get all the entities right from the beginning? I cannot start another entity generator that has association with existing entity, jhipster-uml gets stuck and never recovers.

**Comment by MathieuAA** [comment] 2016-02-08 07:53
There seems to be an issue with your setup, or a InquirerJS introduced a regression. What is your OS, version of Node, version of JHipster UML?

**Comment by dhafirnz** [comment] 2016-02-09 06:13
Hi Mathieu,
OS: Windows 10 running Git Bash 2.7.1 64 bit
node version: 5.4.0
JHipster-UML version: 1.6.1

**Comment by MathieuAA** [comment] 2016-02-09 08:05
As it is related to your other post, I'm closing this one (I will still try to reproduce this issue later today).

**Closed by MathieuAA** 2016-02-09 08:05 UTC
