### ISSUE TITLE
Global install failure

### ISSUE THREAD

**Issue by interstellerS** [jhipster/jhipster-uml#12] opened 2015-06-24 10:11 UTC
Hi , 

I tried installing jhipster-uml : 

```sh
$ npm install -g jhipster-uml  
```
in windows / linux (ubuntu) , it fails with this log output : 

```sh
> deasync@0.1.0 install C:\Users\Administrateur\AppData\Roaming\npm\node_modules\jhipster-uml\node_modules\deasync
> node ./build.js

Build failed
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\iojs\\node.exe" "C:\\Program Files\\iojs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "jhipster-uml"
npm ERR! node v2.3.1
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE

npm ERR! deasync@0.1.0 install: `node ./build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the deasync@0.1.0 install script 'node ./build.js'.
npm ERR! This is most likely a problem with the deasync package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls deasync
npm ERR! There is likely additional logging output above.
```

**Comment by MathieuAA** [comment] 2015-06-24 10:57
Hi,

I just tried the -g option, and everything's fine for me.
I'll do some tests.

**Comment by interstellerS** [comment] 2015-06-24 11:04
Yes , i think jhipster-uml is fine .
it's just related to deasync package that need some sort of envirement installed packages to compile .
```sh
npm ERR! This is most likely a problem with the deasync package,

```

**Comment by MathieuAA** [comment] 2015-06-24 11:08
I'll try to test the installation of everything on a clean (no node, no package) machine, and see if it fails.

Does the standard way to install a package work for you? By standard I mean `npm install jhipster-uml`.

**Comment by interstellerS** [comment] 2015-06-24 11:20
I get the same error as global install .

**Comment by MathieuAA** [comment] 2015-06-24 11:30
Maybe this is caused by your configuration...

I'll try to test on a Windows machine. If it can't build deasync, then something must be missing.

**Comment by interstellerS** [comment] 2015-06-24 11:36
Right , installing deasync lead to same problem .
You can go ahead an close this issue . thanks for you quick reply :+1:  .

**Comment by MathieuAA** [comment] 2015-06-24 11:45
If you can't install deasync, then an alternative to deasync must be found.
I'll close this thread and open another to replace this package, or find a way to install it everywhere.

**Closed by MathieuAA** 2015-06-24 11:45 UTC

**Comment by interstellerS** [comment] 2015-06-24 12:59
I confirm it's a configuration issue (installing Python , MS express ....)  like explained in this git : 

https://gist.github.com/nullivex/7115612

fix deasync issue ans jhipster-uml is installed like charm .

**Comment by MathieuAA** [comment] 2015-06-24 13:02
Ok! Nice to hear it =)

**Comment by interstellerS** [comment] 2015-06-24 14:07
Yup , jhipster is really cool . thx for your work !

Unrelated question : does jhypster-uml generate Enumuration attiributes ?

I modelled an Enum in the uml but in code i just get the name 

```sh
@Column(name = "sport")
    private  sport;
```
Instead of 

```sh
@Column(name = "sport")
    private  Sport sport;
```

**Comment by MathieuAA** [comment] 2015-06-24 14:16
As JHipster doesn't support Enums (to my knowledge), we don't support them either.

**Comment by interstellerS** [comment] 2015-06-24 14:31
There's an issue about that :  [Enums in Jhipster] .

And a pull request is being merged 3 days ago : [Use enumeration for field type] .

[Enums in Jhipster]:https://github.com/jhipster/generator-jhipster/pull/1531 
[Use enumeration for field type]: https://github.com/jhipster/generator-jhipster/pull/1531

I guess it's too early to be implemented in jshipster-uml .  Could this be supported in future version ? :)

**Comment by CarlKlagba** [comment] 2015-06-24 14:42
We want the users to be able to do the same things that they can do with JHipster but faster, so yes we will implement it, but for now we are focusing on some pretty neat new stuff for JHipster-UML. ;)
