### ISSUE TITLE
Type Void not supported

### ISSUE THREAD

**Issue by wadael** [jhipster/jhipster-uml#95] opened 2015-12-29 10:14 UTC
Hi, my latest issue when trying to generate from an XMI (made with Visual Paradigm), from existing Java entities (used java sources)

In an effort to make my model simpler, I dropped all usages of generics (error was DateTime type not supported, same with ZonedDateTime)

C:\Users\jb\hips\h4>jhipster-uml socle2.uml -f 
Parser detected: VISUAL PARADIGM.

```java
The type 'Void' isn't supported by JHipster, exiting now.
Error
    at Object.<anonymous> (C:\Users\jb\AppData\Roaming\npm\node_module
s\jhipster-uml\lib\exceptions\invalid_type_exception.js:7:34)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\jb\AppData\Roaming\npm\node_module
s\jhipster-uml\lib\editors\modelio_parser.js:6:28)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
```

As per grep, the type Void is only found in jhipster 3 generated files
* _UserResource.java (node_modules/generator_jhipster/app/templates/src/main/java/package/web/rest)
* _EntityResource.java (node_modules/generator_jhipster/entity/templates/src/main/java/package/web/rest)
* UserResource.java (src/main)

**Comment by wadael** [comment] 2015-12-29 10:33
Added a ZonedDateTime primitive in my model 
Replaced all java.util.Date usages by ZonedDateTime

Same error

**Comment by MathieuAA** [comment] 2015-12-29 12:16
Hi. From your stacktrace, I see the error was thrown from the parser dealing with Modelio...
Can you copy/paste your XMI file's content?

**Comment by wadael** [comment] 2015-12-29 13:12
Sorry Mathieu, I can't share it all (belongs to company, is 1.2Mb of xml crap). 
There is no mention of modelio in the source.
Here is the start. 

```
<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.1" xmlns:Socle_profile="http:///schemas/Socle_profile/0" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" xmlns:uml="http://www.eclipse.org/uml2/2.0.0/UML" xmlns:xmi="http://schema.omg.org/spec/XMI/2.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http:///schemas/Socle_profile/0 socle2.profile.uml#XzoiF4qAUAQIFwUv_content">
	<uml:Model name="Socle" xmi:id="XzoiF4qAUAQIFwUv">
		<xmi:Documentation exporter="Visual Paradigm" exporterVersion="7.0.2">
			<xmi:Extension extender="Visual Paradigm">
```

Is there a specific part you want to look at ? (give me xpath)

Unluckily, Modelio 3.4 crashes at start on my pc.
Will try another recommended uml tool ...

**Comment by MathieuAA** [comment] 2015-12-29 13:25
Thanks, I'll look at it later (quite busy right now).
I suggest you try the 3.4.1 version of Modelio if you can (you need Java 8 by the way).

**Comment by wadael** [comment] 2015-12-29 13:46
Thank you.
Indeed, starts w/ Java8  :)

**Comment by MathieuAA** [comment] 2015-12-29 15:28
What version of the JHipster generator do you have? and JHipster-UML?

**Comment by wadael** [comment] 2015-12-29 15:39
The latest I believe. I started using JHipster days ago

jhipster-uml@1.5.2
generator-jhipster@2.26.1

I looked in the package.json files, as there is no    jhipster-uml -version  parameter

**Comment by MathieuAA** [comment] 2015-12-30 21:59
Concerning the main "issue", try to look for a type named "Void" in your XMI file (I highly recommend using a search function as Visual Paradigm always produces huge files).
My idea is that, even if this type is not used anymore and can not be seen in the diagram, the file may still contain a reference.
Concerning the problem with the editor detector, I'll do some tests tomorrow with the beginning of your file.

**Comment by wadael** [comment] 2015-12-30 22:04
Hi Mathieu,

There was no Void in the xmi.
I will not be able to give you more file content for a few days.


2015-12-30 22:59 GMT+01:00 Mathieu ABOU-AICHI <notifications@github.com>:

> Concerning the main "issue", try to look for a type named "Void" in your
> XMI file (I highly recommend using a search function as Visual Paradigm
> always produces huge files).
> My idea is that, even if this type is not used anymore and can not be seen
> in the diagram, the file may still contain a reference.
> Concerning the problem with the editor detector, I'll do some tests
> tomorrow with the beginning of your file.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jhipster/jhipster-uml/issues/95#issuecomment-168080882>
> .
>



-- 
Jérôme ( Wadaël )
http://www.wadael.org  _  http://blog.wadael.org

**Comment by MathieuAA** [comment] 2016-01-08 23:00
I can't reproduce it. What bothers me is the Modelio mention, even though you used Visual Paradigm.
I'm closing this thread and labelling it.

**Closed by MathieuAA** 2016-01-08 23:00 UTC
Labels: Can't reproduce
