### ISSUE TITLE
Can't generate 'required' constraints on Modelio Enumeration Attribute

### ISSUE THREAD

**Issue by sebastienmoreno** [jhipster/jhipster-uml#130] opened 2016-02-01 16:25 UTC
Hi,
I put an Enumeration Data Type in Modelio. 
When I try to had it with a 'required' contraint it throw me the following message:

> Cannot read property 'name' of undefined
> TypeError: Cannot read property 'name' of undefined
>     at null.<anonymous> (C:\smo\data\npm-home\npm\node_modules\jhipster-uml\lib\editors\modelio_parser.js:263:96)
>     at Array.forEach (native)
>     at ModelioParser.fillConstraints (C:\smo\data\npm-home\npm\node_modules\jhipster-uml\lib\editors\modelio_parser.js:255:34)
>     at ModelioParser.parse (C:\smo\data\npm-home\npm\node_modules\jhipster-uml\lib\editors\modelio_parser.js:31:8)
>     at Object.<anonymous> (C:\smo\data\npm-home\npm\node_modules\jhipster-uml\jhipster-uml.js:77:27)
>     at Module._compile (module.js:435:26)
>     at Object.Module._extensions..js (module.js:442:10)
>     at Module.load (module.js:356:32)
>     at Function.Module._load (module.js:311:12)
>     at Function.Module.runMain (module.js:467:10)
> 

When I remove the constraint the generation do not throw errors and end ok.
Do you have the same issue?

**Comment by MathieuAA** [comment] 2016-02-01 16:27
Hi, how do you add this constraint? (a screenshot/a sample of your XMI file would be nice).

**Comment by sebastienmoreno** [comment] 2016-02-01 16:32
Here is a sample of the constraint:
`
<ownedRule xmi:type="uml:Constraint" xmi:id="_r2JAlMj2EeWw9bk8gKZX8Q" name="required" constrainedElement="_r2SKpMj2EeWw9bk8gKZX8Q">
    <specification xmi:type="uml:LiteralString" xmi:id="_r2JAlcj2EeWw9bk8gKZX8Q" value="&lt;Enter constraint text here&gt;"/>
  </ownedRule>
`
And the class:
`
<packagedElement xmi:type="uml:Class" xmi:id="_r2SKocj2EeWw9bk8gKZX8Q" name="Answer">
    <ownedAttribute xmi:type="uml:Property" xmi:id="_r2SKosj2EeWw9bk8gKZX8Q" name="implementation" visibility="public" type="_r2JAy8j2EeWw9bk8gKZX8Q" aggregation="composite" association="_r2SKpsj2EeWw9bk8gKZX8Q">
      <lowerValue xmi:type="uml:LiteralInteger" xmi:id="_r2SKo8j2EeWw9bk8gKZX8Q"/>
    </ownedAttribute>
    <ownedAttribute xmi:type="uml:Property" xmi:id="_r2SKpMj2EeWw9bk8gKZX8Q" name="status" visibility="public" type="_r2SKqMj2EeWw9bk8gKZX8Q" isUnique="false"/>
    <ownedAttribute xmi:type="uml:Property" xmi:id="_r2SKpcj2EeWw9bk8gKZX8Q" name="comment" visibility="public" isUnique="false">
      <type xmi:type="uml:PrimitiveType" href="http://www.omg.org/spec/UML/20110701/PrimitiveTypes.xmi#String"/>
    </ownedAttribute>
  </packagedElement>
`

**Comment by MathieuAA** [comment] 2016-02-01 19:31
I know why! We never check for enums as types. I'm gonna fix it, test it, and commit the fix. Sorry for the incovenience!

**Comment by MathieuAA** [comment] 2016-02-01 19:48
The issue is fixed, it will be released with v1.6.1. Thanks for reporting it

**Closed by MathieuAA** 2016-02-01 19:48 UTC
Labels: bug, modelio, visual paradigm

**Comment by sebastienmoreno** [comment] 2016-02-01 20:27
Ok, Mathieu ! 
Thanks for your work !
