### ISSUE TITLE
Relationship to the User entity

### ISSUE THREAD

**Issue by kalvarez2** [jhipster/jhipster-uml#45] opened 2015-08-20 18:16 UTC
Tried to create a very simple sample app using:
     jhipster-uml dataModelSimple.jh -db sql -paginate
Where dataModelSimple.jh is this model:
````
entity User{
}

entity DealershipEmployee{
	id Long required,
	firstname String required,
	lastname String required
}
relationship OneToOne{
	DealershipEmployee{user} to User{dealershipEmployee}
}
````
Did not receive any error past the expected warning about the User entity would be ignored, tried also with ManyToOne instead of OneToOne, same behavior:

The application gets created  successfullyand it is usable, but the DealerhipEmployee does not contain a reference to the User table. I looked in the issues, and there are some about the User entity, but nothing with no errors or warning, maybe I am doing something wrong...

thanks for any help, great tools, both jhipster and the idea of jml...!

**Comment by kalvarez2** [comment] 2015-08-20 20:35
On the entitiescreator.js file, lines 201-208. I understand the current documentation says that User is a reserved entity and any owning relationships will be ignored, but it also says that relationships to the user entity would be honored. 

Is that check for the injected field type removing any relationship to the user?

**Comment by kalvarez2** [comment] 2015-08-20 20:42
Update: I removed that check locally, keeping the check for the class, but removing the check for the type, and that  fixes my problem,at least for OneToOne relationship, no idea what other weird behavior that might introduce...

**Comment by MathieuAA** [comment] 2015-08-21 15:54
I will check this out this week-end.

**Comment by MathieuAA** [comment] 2015-08-22 09:10
Hi! I'm fixing this issue right now. It looks pretty good so far, but I'll need a bit more time to test it.
When the fix is done, I'll push it and make a patch release of it (v1.3.2).

**Comment by MathieuAA** [comment] 2015-08-22 09:33
The fix I'll commit only works for One-to-One relationships, as other relationships will break JHipster's tests (reproduced with and without JHipster-UML's JDL).
So, for now, I'll push the fix for the One-to-One. If the other types or relationships work, then I'll keep adding them.

**Comment by MathieuAA** [comment] 2015-08-22 09:37
(Partially) Fixed by 4837b24.

**Closed by MathieuAA** 2015-08-22 09:37 UTC
Labels: bug

**Comment by andidev** [comment] 2015-08-22 09:53
Many to one and many to many is supported and works in jhipster as it is today. Just tested it yesterday.

**Comment by MathieuAA** [comment] 2015-08-22 10:19
Well, I just tested it with the User class, and the tests fail.

**Comment by andidev** [comment] 2015-08-22 13:25
I successfully created a many to many relation with latest jhipster-uml 1.3.2 which generated the following enity.json:
```json
{
  "relationships": [
    {
      "relationshipId": 1,
      "relationshipName": "aUser",
      "relationshipFieldName": "aUser",
      "otherEntityName": "user",
      "relationshipType": "many-to-many",
      "otherEntityField": "id",
      "ownerSide": true
    }
  ],
  "fields": [],
  "changelogDate": "20150822131836",
  "dto": "no",
  "pagination": "no"
}
```

`mvn test` and `grunt test` both pass.

Is it only Many to one relationships that fail?

**Comment by andidev** [comment] 2015-08-22 13:57
I also successfully created a many to one relationship to the User entity with the following entity json:
```json
{
    "relationships": [
        {
            "relationshipId": 1,
            "relationshipName": "user",
            "otherEntityName": "user",
            "relationshipType": "many-to-one",
            "otherEntityField": "id"
        }
    ],
    "fields": [
        {
            "fieldId": 1,
            "fieldName": "name",
            "fieldType": "String"
        }
    ],
    "changelogDate": "20150822135227",
    "dto": "no",
    "pagination": "no"
}
```

both `mvn test` and `grunt test` works and I can update the user relationship in the gui.

Could you please provide the json files for the failing tests so I can try to fix them?

**Comment by MathieuAA** [comment] 2015-08-22 17:03
The code I got looks like yours... Gotta recheck. I'll post the code as soon as I get back to my computer.

**Comment by andidev** [comment] 2015-08-22 17:55
By the way, just to be clear, I used the current master branch of jhipster. Though I think it works with the latest release as well.

**Comment by MathieuAA** [comment] 2015-08-22 19:42
Just got back. I'm using the latest code available of both JHipster and JHipster-UML.
The M2M, the O2O and the M2O work, but not the O2M, which is just crazy because adding the last entity makes my tests fail (all of them, not just the ones for the last entity).

Here are all the .json, hope you can make some sense out of this mess.
TestA.json:
```json
{
    "relationships": [
        {
            "relationshipId": 1,
            "relationshipName": "user",
            "otherEntityName": "user",
            "relationshipType": "many-to-one",
            "otherEntityField": "id"
        }
    ],
    "fields": [],
    "changelogDate": "20150822193205",
    "dto": "no",
    "pagination": "no"
}

```

TestB:

```json
{
    "relationships": [
        {
            "relationshipId": 1,
            "relationshipName": "user",
            "otherEntityName": "user",
            "relationshipType": "many-to-many",
            "otherEntityField": "id",
            "ownerSide": true
        }
    ],
    "fields": [],
    "changelogDate": "20150822193343",
    "dto": "no",
    "pagination": "no"
}

```


```json
{
    "relationships": [
        {
            "relationshipId": 1,
            "relationshipName": "user",
            "otherEntityName": "user",
            "relationshipType": "one-to-many",
            "otherEntityRelationshipName": "testC"
        }
    ],
    "fields": [],
    "changelogDate": "20150822193437",
    "dto": "no",
    "pagination": "no"
}

```

I see an error in the JSON generated from JHipster-UML however, the `relationshipFieldName` shouldn't be there for the M2M.

**Comment by andidev** [comment] 2015-08-23 11:08
I'm not sure but I think that test C fails cause one to many relationship (where the user is the owner) with the user entity is not supported by jhipster.

**Comment by MathieuAA** [comment] 2015-08-23 15:23
That should be the normal behavior... however, how come my TestC entity is not the owner of the relationship? If I set a O2M from TestC to User, then TestC should be the owner, right? Unless I'm missing some convention here...

**Comment by andidev** [comment] 2015-08-23 16:31
I think it's the other way around. The Many entity will be the owner. According to the docs the many entity is the right one. 

```
relationship OneToMany{
  One{many} to Many{one(<otherEntityField>)}
}
```

**Comment by MathieuAA** [comment] 2015-08-23 16:57
If that's the case, there's some weird logic involved... 
In JDL, the first is the owner (that's why we chose to say <XXX> to <YYY>). If in JHipster, when creating a O2M, the current entity is not the owner, then something's wrong, in my opinion.

I clearly don't understand the logic behind it.

**Comment by andidev** [comment] 2015-08-23 18:36
In jhipster when creating an O2M the current entity is never the owner. The many entity is always the owner in a O2M relationship. 

You say that in jdl that the first entity is always the owner. That is not true. It is the first entity that is the owner for M2O, O2O and M2M relationships but not the O2M. In fact te first one could never always be the owner since the O2M is the inverse of the M2O relationship.

**Comment by MathieuAA** [comment] 2015-08-23 18:45
That's strange. The doc says otherwise, and (until now) I thought the same. Anyway, my bad.

**Comment by kalvarez2** [comment] 2015-08-23 18:55
Guys, my two cents if i may...
-it makes sense not to create a list of other entities in a class by
default. It might be harder to optimize later... it is one lesson I have
learned. So it makes sense that jhipster doesnt do it. I am perosnally ok
with that.

-i understand user is an special entity and changes are not alowed, but
having a reference to user in a clas produced by a o2o or m2o seems like a
very usefull feature.

I am a software developer with some experience. I have found jhipster and
jml both very usefull and would like to give back some of my time, anything
you guys would like me to handle?

**Comment by andidev** [comment] 2015-08-23 19:46
@MathieuAA
I think one reason for the confusion may be that jhipster never asks for the owner side when creating a one-to-many and many-to-one relationship. The ownerSide property is not even set in the entity json for that kind of relationships. Instead the ownerSide is determined by the relationship type.

@kalvarez2
PR improvements are always welcome, not sure what needs to be done here though =)

**Comment by kalvarez2** [comment] 2015-08-28 23:02
great work guys!
@andidev 
is there a list of requests somewhere? How about supporting comments on jdl, I have one with 16 entities and the relationships are hard to folow with no comments, I was looking at the parser that was generated, seems posible to add a new rule to ignore comments as white space with a regex?
Again, is there a "nice to have list"?

**Comment by andidev** [comment] 2015-08-29 05:56
I think there is no list other than the issue list though I am not the author of jhipster-uml so you should probably ask @CarlKlagba or @MathieuAA for this.

**Comment by MathieuAA** [comment] 2015-08-29 08:29
For comments on JDL, I or @CarlKlagba will work on that very soon, and we'll parse comments from XMI too.
And as @andidev said, there's no list. People just drop by and post an "issue" on GitHub, which is bad enough... They should have renammed it "ticket" instead.
