### ISSUE TITLE
Relationships are repeated for unknown reasons

### ISSUE THREAD

**Issue by javasparx** [jhipster/jhipster-uml#106] opened 2016-01-08 06:46 UTC
I have already used jhipster and jhipster-uml in some projects before without any problem. Now I'm trying to generate entities using JHipster-UML generator in my new project, but have repeating problem (see customer and owner relationships in TransLits entity). Give me advice if I'm doing sth wrong, please.

Versions:
generator-jhipster@2.26.2
jhipster-uml@1.5.2
npm@3.5.2
yeoman-generator@0.20.3
yo@1.4.8

Executed command: **jhipster-uml models.jh -paginate**

**models.jh**

```
entity Contract{...}

relationship OneToMany{
    User to Contract{owner(user)}
}

entity Customer{...}

relationship OneToMany{
    User to Customer{owner(user)}
}
relationship OneToMany{
    Customer to Contract{customer}
}

entity TransList{...}

relationship OneToMany{
    Contract to TransList{contract}
}
relationship OneToMany{
    Customer to TransList{customer}
}
relationship OneToMany{
    User to TransList{owner(user)}
}
```

**.jhipster/TransList.json**

```json
{
  "relationships": [
    {
      "relationshipId": 1,
      "relationshipName": "contract",
      "otherEntityName": "contract",
      "relationshipType": "many-to-one",
      "otherEntityField": "id"
    },
    {
      "relationshipId": 2,
      "relationshipName": "customer",
      "otherEntityName": "customer",
      "relationshipType": "many-to-one",
      "otherEntityField": "id"
    },
    {
      "relationshipId": 3,
      "relationshipName": "customer",
      "otherEntityName": "customer",
      "relationshipType": "many-to-one",
      "otherEntityField": "id"
    },
    {
      "relationshipId": 4,
      "relationshipName": "transType",
      "otherEntityName": "transType",
      "relationshipType": "many-to-one",
      "otherEntityField": "id"
    },
    {
      "relationshipId": 5,
      "relationshipName": "owner",
      "otherEntityName": "user",
      "relationshipType": "many-to-one",
      "otherEntityField": "user"
    },
    {
      "relationshipId": 6,
      "relationshipName": "owner",
      "otherEntityName": "user",
      "relationshipType": "many-to-one",
      "otherEntityField": "user"
    },
    {
      "relationshipId": 7,
      "relationshipName": "owner",
      "otherEntityName": "user",
      "relationshipType": "many-to-one",
      "otherEntityField": "user"
    }
  ],
  "fields": [
    ...
  ],
  "changelogDate": "20160108055117",
  "dto": "no",
  "pagination": "pagination"
}
```

Thank you in advance!

**Comment by MathieuAA** [comment] 2016-01-08 08:00
Hello. You have to remove the pagination flag when having a JDL file.
I'll add it to the doc.

**Comment by javasparx** [comment] 2016-01-08 08:52
Hello. Is your comment related to my question?

To be clear, my entity has same relationships:

```
{
      "relationshipId": 2,
      "relationshipName": "customer",
      "otherEntityName": "customer",
      "relationshipType": "many-to-one",
      "otherEntityField": "id"
    },
    {
      "relationshipId": 3,
      "relationshipName": "customer",
      "otherEntityName": "customer",
      "relationshipType": "many-to-one",
      "otherEntityField": "id"
    }
```

**Comment by MathieuAA** [comment] 2016-01-08 09:11
It is. Do `jhipster-uml models.jh` instead of `jhipster-uml models.jh -paginate`.

**Comment by javasparx** [comment] 2016-01-08 10:24
Sorry man, it did not solve my problem. Result is same, except pagination.

```
jhipster-uml models.jh
```

```
"pagination": "no"
```

**Comment by MathieuAA** [comment] 2016-01-08 10:33
You have to read the doc for that, [here](http://jhipster.github.io/jhipster_uml.html#options) =).
When you have a JDL file, you have to specify how to generate paginations, services, DTOs.

**Comment by MathieuAA** [comment] 2016-01-08 10:36
Oh. Didn't see the other problem. I'll look at it later.

**Comment by javasparx** [comment] 2016-01-08 10:55
I am using jhipster-uml@1.5.2 (the latest release), not version 1.6.0. And I see, version 1.6.0 is more "powerful"!

**Comment by MathieuAA** [comment] 2016-01-08 23:53
I didn't solve this case yet. But your JDL file is wrong (this doesn't solve anything I'm affraid, but it's still a mistake).
When you use `User to Customer{owner(user)}`, you expect the `Customer` to have an `owner` attribute (a User), and this User is identified by its `user` attribute. The problem is the `User` class doesn't have a `user` attribute.

**Comment by javasparx** [comment] 2016-01-11 05:41
Thank you, I fixed "owner.user" bug.

**I am using jhipster-uml@1.5.2 (the latest release)**
Till now, I defined that every binding to User is added in to the last entity binded to the User:

**models.jh**
```
entity Contract{}

entity Customer{}

relationship OneToMany{
    User to Customer{customerOwner}
}

relationship OneToMany{
    User to Contract{owner}
}

entity TransList{}

relationship OneToMany{
    User to TransList{transOwner}
}

```

**Contact.json**
```
"relationships": []
```

**Customer.json**
```
"relationships": []
```

**TransList.json**
```
"relationships": [    
    {
      "relationshipId": 1,
      "relationshipName": "transOwner",
      "otherEntityName": "user",
      "relationshipType": "many-to-one",
      "otherEntityField": "id"
    },
    {
      "relationshipId": 2,
      "relationshipName": "transOwner",
      "otherEntityName": "user",
      "relationshipType": "many-to-one",
      "otherEntityField": "id"
    },
    {
      "relationshipId": 3,
      "relationshipName": "transOwner",
      "otherEntityName": "user",
      "relationshipType": "many-to-one",
      "otherEntityField": "id"
    }
  ]
```

**Comment by javasparx** [comment] 2016-01-11 05:42
Could you tell date of release 1.6.0?

**Comment by MathieuAA** [comment] 2016-01-11 08:04
Before the end of the month I hope. But I doubt your issue will be fixed by the release... I may have a solution, but I need some time to develop and test it (I will include it in the release if I finish it before).

**Comment by MathieuAA** [comment] 2016-01-14 12:24
Work is being done in the new_parsed_data branch.

**Comment by javasparx** [comment] 2016-01-14 12:49
nice to hear it.

**Comment by javasparx** [comment] 2016-01-17 16:46
Hi Mathieu, do u have any news?

**Comment by MathieuAA** [comment] 2016-01-17 16:50
Yes. I upgraded all the parsers (for the four editors and the JDL). Actually upgrading the JSON creator and then I'll work on the scheduler. The tests are finished for the parsers, but ony them have their tests done.
I'll wrap it up by the end of the week.

**Comment by javasparx** [comment] 2016-01-17 19:20
Thank you. I look forward to the next release.

**Comment by MathieuAA** [comment] 2016-01-20 20:44
The implementation is finished. Try to clone the repo and switch to the `new_parsed_data` branch to test it.
If yo are unsure about the commands, here they are:

    git clone https://github.com/jhipster/jhipster-uml.git
    cd jhipster-uml
    git checkout new_parsed_data
    npm link

I will merge and release after I implement some tests.

**Comment by MathieuAA** [comment] 2016-01-20 21:17
Just tested with the latest version, it seems to work... I may merge it sooner than planned!

**Comment by javasparx** [comment] 2016-01-21 12:56
It will be great!

**Comment by javasparx** [comment] 2016-01-22 18:54
Good job @MathieuAA!!! I tested new_parsed_data and it works pretty well.

By the way, do u plan to support precision and scale configuration for numbers?

**Comment by MathieuAA** [comment] 2016-01-22 19:07
Thank you for testing =) one more bug to kill before merging and releasing!
As far as I know, JHipster doesn't support it yet, so we won't add it (unless they do, of course!).

**Closed** 2016-01-22 21:28 UTC
Labels: bug, JDL
