### ISSUE TITLE
CircularDependencyException when generating Oracle hr sample (using Modelio)

### ISSUE THREAD

**Issue by tsukhu** [jhipster/jhipster-uml#7] opened 2015-06-13 13:32 UTC
I was trying to follow the extact steps to generate the Oracle HR Data model as provided on your site  . Given below is the data model screen shot from Modelio
![hrapp](https://cloud.githubusercontent.com/assets/846306/8144480/224eb588-11fe-11e5-99e3-57c539dc94d8.png)

however when I run it I get this error. It would be great if you could let me know want am I doing wrong here ?

tsukhu@ubuntu64:~/hrapp$ jhipster-uml ../hrapp.xmi sql
Parser detected: MODELIO.

/usr/lib/node_modules/jhipster-uml/lib/scheduler.js:83
      throw new CircularDependencyException(
            ^
Error
    at Object.<anonymous> (/usr/lib/node_modules/jhipster-uml/lib/scheduler.js:178:41)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/lib/node_modules/jhipster-uml/jhipster-uml.js:16:22)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)

**Comment by MathieuAA** [comment] 2015-06-13 14:58
Hi,

It may have been caused by the bidirectionnal relationship between Job and Task.

Have a look at [this example](http://jhipster.github.io/managing_relationships.html#5), detailing how it is implemented and handled by JHipster.

Hope it helps.

**Comment by tsukhu** [comment] 2015-06-13 16:52
Thanks a lot !! This fixed the issue.. 
Here is what I changed
![hrapp_modifiedpng](https://cloud.githubusercontent.com/assets/846306/8145156/5fe0b1fa-121a-11e5-8eb2-289aaac7f309.png)

However there is one thing missing though .. the AngularJS side code for the relationship for example the dropdown of the departments for the Employees .. I guess that is due to the missing "otherEntityField" attribute. Is that planned in the future ?

**Comment by MathieuAA** [comment] 2015-06-13 17:25
Happy to have helped you =)

You could have put 'jobs' in the many-to-many relationship (both are expected anyway).

I tested the creation an app using the last version of JHipster and the standard Q&A (I made a bidirectionnal relationship), and there is no other 'otherEntityField' by default (I guess there wouldn't be any with a unidirectionnal).
If you want, you can ask [there](https://github.com/jhipster/generator-jhipster/issues) if this feature can be implemented (or even better propose a PR).

I'm closing this thread as the original problem has been solved.

**Closed by MathieuAA** 2015-06-13 17:25 UTC
