### ISSUE TITLE
"Cannot read property 'forEach' of undefined" when trying to use enumerators in Modelio

### ISSUE THREAD

**Issue by geraldhumphries** [jhipster/jhipster-uml#54] opened 2015-09-14 20:47 UTC
## Overview of the issue
When I use the "Enumeration" type in Modelio then try to generate the entities through JHipster, I get the following:

````
$ jhipster-uml uml.xmi
Parser detected: MODELIO.

Cannot read property 'forEach' of undefined
TypeError: Cannot read property 'forEach' of undefined
    at null.<anonymous> (c:\Users\ghumphries\AppData\Roaming\npm\node_modules\jhipster-uml\lib\editors\modelio_parser.js:87:29)
    at Array.forEach (native)
    at ModelioParser.fillEnums (c:\Users\ghumphries\AppData\Roaming\npm\node_modules\jhipster-uml\lib\editors\modelio_parser.js:81:24)
    at ModelioParser.parse (c:\Users\ghumphries\AppData\Roaming\npm\node_modules\jhipster-uml\lib\editors\modelio_parser.js:21:8)
    at Object.<anonymous> (c:\Users\ghumphries\AppData\Roaming\npm\node_modules\jhipster-uml\jhipster-uml.js:69:27)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
````

I've tried generating without the enums, and I have a circular reference that I haven't figured out yet if that makes a difference. There is nothing in the docs about enumerators in Modelio so I might just be doing something wrong.

## Motivation for or Use Case
This is blocking me from using the generator.

## JHipster-UML version
1.4.2

## JHipster configuration
I can upload my xmi file and .yo-rc.json somewhere if needed.

## Operating System
Windows 10

**Comment by MathieuAA** [comment] 2015-09-15 07:12
Hi, I'd like to see your XMI file please!
If there's an error when generating enums with Modelio, then the tests need fixing too as they didn't detect it.
For the docs, I'm planning to update them very soon (friday I hope) but didn't PR because of the lack of time.

**Comment by geraldhumphries** [comment] 2015-09-15 13:58
What is the best way for me to upload the file?

**Comment by MathieuAA** [comment] 2015-09-15 14:58
You can either copy/paste it here, or send it to my email address (mabouaichi@ippon.fr).
I'd suggest you pass it here so that everyone can work on it (if you want to, of course).

**Comment by geraldhumphries** [comment] 2015-09-15 15:07
I would prefer to keep it private, so I'll send you an email.

**Comment by MathieuAA** [comment] 2015-09-15 20:08
I managed to reproduce your error with your XMI file.
The enum problem came from a simple assumption I made: that all enums have at least one field called `ownedLiteral`, but this assumption is false if an enum doesn't possess any value (the origin of your error). I'm going to commit a fix right soon, so you can test and I can release a patch ASAP.

I'm seeing what causes the circular dependency right now...

**Comment by geraldhumphries** [comment] 2015-09-15 20:39
So it was mostly an issue with the schema - the design I sent you is unfinished, which is why a lot of the enums have no values.

**Comment by MathieuAA** [comment] 2015-09-16 04:57
As far I am concerned, the parsers were supposed to handle this case in the first place (and now they can).
If the problem's solved for you, I will close this thread and release a patch today.

**Comment by geraldhumphries** [comment] 2015-09-16 15:31
Yes, the issue is fixed. Thanks.

Don't worry about the circular dependency, I've got some learning to do.

**Closed** 2015-09-16 17:05 UTC
