### ISSUE TITLE
installing jhipster-uml in docker returns error (permission denied)

### ISSUE THREAD

**Issue by alireza-hanifi** [jhipster/jhipster-uml#193] opened 2016-06-17 00:48 UTC
### The issue
when i using jhipster docker image, i am not be able to use jhipster-uml.

i followed docker installation step by step from documentation
at the end i entered following command .
docker exec -it jhipster bash
but it returned permission denied.
i using the last version of docker image. and my os is ubuntu 16.04.

---
#### The stacktrace

```
npm ERR! Linux 4.4.0-24-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "jhipster-uml"
npm ERR! node v4.4.5
npm ERR! npm  v3.9.5
npm ERR! path ../lib/node_modules/jhipster-uml/jhipster-uml.js
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall symlink

npm ERR! Error: EACCES: permission denied, symlink '../lib/node_modules/jhipster-uml/jhipster-uml.js' -> '/usr/bin/jhipster-uml'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES: permission denied, symlink '../lib/node_modules/jhipster-uml/jhipster-uml.js' -> '/usr/bin/jhipster-uml']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'symlink',
npm ERR!   path: '../lib/node_modules/jhipster-uml/jhipster-uml.js',
npm ERR!   dest: '/usr/bin/jhipster-uml' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.
npm ERR! Linux 4.4.0-24-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "jhipster-uml"
npm ERR! node v4.4.5
npm ERR! npm  v3.9.5
npm ERR! path npm-debug.log.2188898570
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall open

npm ERR! Error: EACCES: permission denied, open 'npm-debug.log.2188898570'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES: permission denied, open 'npm-debug.log.2188898570']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'open',
npm ERR!   path: 'npm-debug.log.2188898570' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/jhipster/app/npm-debug.log

```

**Comment by MathieuAA** [comment] 2016-06-17 05:46
Hi, it's a node issue: using sudo or any other privilege granting command shouldn't be done... Either the doc about it is wrong or docker+node+npm sucks...
There's a page dealing with this on NPM's doc (right issue). You should check it out.

Le 17 juin 2016 02:48:01 GMT+02:00, Alireza <notifications@github.com> a écrit :
>### The issue
>when i using jhipster docker image, i am not be able to use
>jhipster-uml.
>
>i followed docker installation step by step from documentation
>at the end i entered following command .
>docker exec -it jhipster bash
>but it returned permission denied.
>
>i using the last version of docker image. and my os is ubuntu 16.04
>---
>#### The stacktrace
>
>```
>npm ERR! Linux 4.4.0-24-generic
>npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g"
>"jhipster-uml"
>npm ERR! node v4.4.5
>npm ERR! npm  v3.9.5
>npm ERR! path ../lib/node_modules/jhipster-uml/jhipster-uml.js
>npm ERR! code EACCES
>npm ERR! errno -13
>npm ERR! syscall symlink
>
>npm ERR! Error: EACCES: permission denied, symlink
>'../lib/node_modules/jhipster-uml/jhipster-uml.js' ->
>'/usr/bin/jhipster-uml'
>npm ERR!     at Error (native)
>npm ERR!  { [Error: EACCES: permission denied, symlink
>'../lib/node_modules/jhipster-uml/jhipster-uml.js' ->
>'/usr/bin/jhipster-uml']
>npm ERR!   errno: -13,
>npm ERR!   code: 'EACCES',
>npm ERR!   syscall: 'symlink',
>npm ERR!   path: '../lib/node_modules/jhipster-uml/jhipster-uml.js',
>npm ERR!   dest: '/usr/bin/jhipster-uml' }
>npm ERR! 
>npm ERR! Please try running this command again as root/Administrator.
>npm ERR! Linux 4.4.0-24-generic
>npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g"
>"jhipster-uml"
>npm ERR! node v4.4.5
>npm ERR! npm  v3.9.5
>npm ERR! path npm-debug.log.2188898570
>npm ERR! code EACCES
>npm ERR! errno -13
>npm ERR! syscall open
>
>npm ERR! Error: EACCES: permission denied, open
>'npm-debug.log.2188898570'
>npm ERR!     at Error (native)
>npm ERR!  { [Error: EACCES: permission denied, open
>'npm-debug.log.2188898570']
>npm ERR!   errno: -13,
>npm ERR!   code: 'EACCES',
>npm ERR!   syscall: 'open',
>npm ERR!   path: 'npm-debug.log.2188898570' }
>npm ERR! 
>npm ERR! Please try running this command again as root/Administrator.
>
>npm ERR! Please include the following file with any support request:
>npm ERR!     /home/jhipster/app/npm-debug.log
>
>```
>
>
>---
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/jhipster/jhipster-uml/issues/193

-- 
Mathieu ABOU-AICHI

**Comment by MathieuAA** [comment] 2016-06-17 05:54
This link https://docs.npmjs.com/getting-started/fixing-npm-permissions should help you.

Le 17 juin 2016 02:48:01 GMT+02:00, Alireza <notifications@github.com> a écrit :
>### The issue
>when i using jhipster docker image, i am not be able to use
>jhipster-uml.
>
>i followed docker installation step by step from documentation
>at the end i entered following command .
>docker exec -it jhipster bash
>but it returned permission denied.
>
>i using the last version of docker image. and my os is ubuntu 16.04
>---
>#### The stacktrace
>
>```
>npm ERR! Linux 4.4.0-24-generic
>npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g"
>"jhipster-uml"
>npm ERR! node v4.4.5
>npm ERR! npm  v3.9.5
>npm ERR! path ../lib/node_modules/jhipster-uml/jhipster-uml.js
>npm ERR! code EACCES
>npm ERR! errno -13
>npm ERR! syscall symlink
>
>npm ERR! Error: EACCES: permission denied, symlink
>'../lib/node_modules/jhipster-uml/jhipster-uml.js' ->
>'/usr/bin/jhipster-uml'
>npm ERR!     at Error (native)
>npm ERR!  { [Error: EACCES: permission denied, symlink
>'../lib/node_modules/jhipster-uml/jhipster-uml.js' ->
>'/usr/bin/jhipster-uml']
>npm ERR!   errno: -13,
>npm ERR!   code: 'EACCES',
>npm ERR!   syscall: 'symlink',
>npm ERR!   path: '../lib/node_modules/jhipster-uml/jhipster-uml.js',
>npm ERR!   dest: '/usr/bin/jhipster-uml' }
>npm ERR! 
>npm ERR! Please try running this command again as root/Administrator.
>npm ERR! Linux 4.4.0-24-generic
>npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g"
>"jhipster-uml"
>npm ERR! node v4.4.5
>npm ERR! npm  v3.9.5
>npm ERR! path npm-debug.log.2188898570
>npm ERR! code EACCES
>npm ERR! errno -13
>npm ERR! syscall open
>
>npm ERR! Error: EACCES: permission denied, open
>'npm-debug.log.2188898570'
>npm ERR!     at Error (native)
>npm ERR!  { [Error: EACCES: permission denied, open
>'npm-debug.log.2188898570']
>npm ERR!   errno: -13,
>npm ERR!   code: 'EACCES',
>npm ERR!   syscall: 'open',
>npm ERR!   path: 'npm-debug.log.2188898570' }
>npm ERR! 
>npm ERR! Please try running this command again as root/Administrator.
>
>npm ERR! Please include the following file with any support request:
>npm ERR!     /home/jhipster/app/npm-debug.log
>
>```
>
>
>---
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/jhipster/jhipster-uml/issues/193

-- 
Mathieu ABOU-AICHI

**Comment by MathieuAA** [comment] 2016-06-17 07:49
@pascalgrimaud is it normal?

**Comment by pascalgrimaud** [comment] 2016-06-17 08:18
no, it's not normal :-D
I will try to reproduce the error tonight

@alireza-hanifi : do you have more input ? All commands you type, with the order

**Comment by alireza-hanifi** [comment] 2016-06-17 10:50
@pascalgrimaud  no i don't enter any command, just i run the container and after that, connecting to it with bash ,at the end i installed jhipster-uml.
@MathieuAA it doesn't help me, because in docker "sudo" not exists. and when i want to change ownership of "/usr/bin" it says the operation not permitted.

**Comment by MathieuAA** [comment] 2016-06-17 11:50
But you don't change the ownership of /usr/bin, the trick is to save the npm_modules folder to another place. There must be a way... Luckily mister Docker here can help you better than I could ;)

Le 17 juin 2016 12:50:25 GMT+02:00, Alireza <notifications@github.com> a écrit :
>@pascalgrimaud  no i don't enter any command, just i run the container
>and after that, connecting to it with bash ,at the end i installed
>jhipster-uml.
>@MathieuAA it doesn't help me, because in docker "sudo" not exists. and
>when i want to change ownership of "/usr/bin" it says the operation not
>permitted.
>
>---
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/jhipster/jhipster-uml/issues/193#issuecomment-226739707

-- 
Mathieu ABOU-AICHI

**Comment by PierreBesson** [comment] 2016-06-17 12:02
OK, I think the fix would be to include JHipster-UML in the docker image itself. We would just need to add  ` jhipster-uml` [here](https://github.com/jhipster/generator-jhipster/blob/master/Dockerfile#L38). @pascalgrimaud would you agree to this change ?

**Comment by MathieuAA** [comment] 2016-06-17 12:24
Good idea Pierre! 

Le 17 juin 2016 14:02:30 GMT+02:00, Pierre Besson <notifications@github.com> a écrit :
>OK, I think the fix would be to include JHipster-UML in the docker
>image itself. We would just need to add  ` jhipster-uml`
>[here](https://github.com/jhipster/generator-jhipster/blob/master/Dockerfile#L38).
>@pascalgrimaud would you agree to this change ?
>
>---
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/jhipster/jhipster-uml/issues/193#issuecomment-226751869

-- 
Mathieu ABOU-AICHI

**Comment by pascalgrimaud** [comment] 2016-06-17 12:36
Not sure, because every new version of jhipster-uml means new Docker image.
Give me time to have a look at this issue (probably tonight) :-)

**Comment by pascalgrimaud** [comment] 2016-06-17 17:45
@alireza-hanifi : can you try
- `docker exec -u root -it jhipster bash`
- `npm install -g jhipster-uml`
- then exit and go into container with normal way: `docker exec -it jhipster bash`

I think the reason is:
- you need to use `sudo npm install -g xxxx`
- but you can't because it seems sudo is not installed by default with the xenial

**Comment by alireza-hanifi** [comment] 2016-06-17 22:32
thanks @pascalgrimaud .
you made my day.
i did not know could connect to docker with root user.
docker exec -u root -it jhipster bash

**Comment by MathieuAA** [comment] 2016-06-18 14:34
Can I close this? (adding this tip in the docs may be a good idea...?)

**Comment by pascalgrimaud** [comment] 2016-06-18 16:21
Yes more information to docs is always welcome

**Comment by MathieuAA** [comment] 2016-06-19 19:38
I've submitted a PR for this. Thanks for reporting this!

**Closed by MathieuAA** 2016-06-19 19:38 UTC
Labels: Doc, question
