### ISSUE TITLE
one-to-many with User in dsl

### ISSUE THREAD

**Issue by openworker** [jhipster/jhipster-uml#33] opened 2015-07-17 03:42 UTC
Hi I'm failing to generate a one-to-many with the User that would be autogenerated in JHipster in subsequent steps.

See functionality that should be availabel here: https://jhipster.github.io/2015/03/01/jhipster-release-2.5.0.html

"The User entity, which is a special entity handled by JHipster, has been modified so you can do many-to-one relationships to it:

This is a common requirement to have some entities linked to the user. For example, many “orders” could be linked to one “user”.
As usually you will want to restrict those entities to the current user, we also provide a helper Repository method, called findAllForCurrentUser() which will be automatically generated
If you have a look at this method, you will see that we use the Spring Security Principal in a Spring Data JPA query. This is because we added SpEL support in Spring Data JPA!"

How is this achievable in Jhipster-uml?

I am testing with a basic sample app using the jhipster-uml dsl code and simply adding:

entity Order{
 note String required minlength(5) maxlength(200)
}
relationship OneToMany{
User{order} to Order{client}
}

When I run jhipster-uml I get:
In the association User_to_Order, the entity User is not declared.
Error
    at Object.<anonymous> (/usr/lib/node_modules/jhipster-uml/lib/dsl/dsl_parser.js:251:39)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/lib/node_modules/jhipster-uml/lib/editors/editors.js:6:18)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)

Thanks for this great project.

**Comment by MathieuAA** [comment] 2015-07-17 10:36
Hi. I'm not the one who coded this, so I don't have any specific idea why it fails, but I'll look into it ASAP.
Maybe @CarlKlagba has an idea on the matter.
Thanks for reporting this issue.

**Comment by CarlKlagba** [comment] 2015-07-17 11:23
The problem is that User isn't declared by default. Try adding an User entity without any thing it. You should only have a warning. 
There is two way to see it:
- The User entity must be explicitly declared in the JDL.
- The User can be implicitly declared when there is a reference to it.  
We are currently in the first case.
I think that the second can be added as an option.
It will be in our next release.

**Closed** 2015-07-21 16:12 UTC
